apiVersion: v1
kind: PersistentVolume
metadata:
  name: static-pv
  namespace: db-devlaba1
spec:
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: financeapp-storage-class
  hostPath:
    path: /mnt/data/financeapp/static
