apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-pvc
  namespace: db-devlaba1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: financeapp-storage-class
